#apache basic web config

<Directory />		#root directory
    Options None	#disbales all special features
    AllowOverride None	#makes sure that the web server follows the main configuration
    Require all denied	#completely denies access to it
</Directory>

<Directory /var/www/>	# the directory to where the files are served at
    Options -Indexes +FollowSymLinks	#prevents users from seeing directory listing
    AllowOverride None
    Require all granted	# compoletely allows everyone to access this directory

    <LimitExcept GET POST>	#blocks PUT/DELETE/etc
      Require all denied
    </LimitExcept>
</Directory>

<FilesMatch "^\.">	#blocks all files with a . in them
    Require all denied
</FilesMatch>

<FilesMatch "(^\.|\.bak|\.old|\.sql|\.zip|\.tar|\.env)$">	#blocks all of these file extensions from running (extra in case someone runs something with an extention)
    Require all denied
</FilesMatch>


#add this information to the bottom or somewhere in the config file
ServerTokens Prod	#tells the web server not to reveal its OS
ServerSignature Off	#tells it not to reveal its signature

TraceEnable off	#disables debugging trace method that can be used in Cross Site tracing attacks

Header always set X-Content-Type-Options "nosniff"	#forces the browser to a declared Content-Type rather than guessing if it is a malicious script
Header always set X-Frame-Options "SAMEORIGIN"	#prevents websites from putting <iframe> in website
Header always set X-XSS-Protection "1; mode=block"	#stops the page from loading if detecting reflected XSS attack
Header set Content-Security-Policy "default-src 'self'"	#tells the browser to only load scripts, images and CSS that came from own domain (will break Google Fonts, YouTube embeds, Bootstrap CDNs, Google Analytics, and more)



#can use the commands below to only allow a certain ip adddress
Require ip 192.168.1 #only allows ips that start with those specific numbers
Require host trusted-partner.com #only allows a specific host
