#nginx.conf

server_tokens off; #removes showing the version 
autoindex off; #makes sure that it will never list all of the files
add_header X-Frame-Options "SAMEORIGIN"; #prevent against clickjacking attacks
add_header X-XSS-Protection "1; mode=block"; #forces the browser to turn on XSS filter
add_header X-Content-Type-Options "nosniff"; #stops the browser from trying to guess the type of the file
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always; #makes sure that the website only talks in https
add_header Referrer-Policy "no-referrer-when-downgrade" always; #makes sure that it only writes the referrer if it is moving to another secure site

limit_req_zone $binary_remote_addr zone=mylimit:10m rate=10r/s; #tracks ip address of user and prevents brute force password guessing and minor DDoS attacks
limit_req zone=mylimit burst=20 nodelay; #briefly allows a spike up to 20 requests at once before the limit kicks in
